(ns jamesmacaulay.zelkova.impl.time
  "Implementation details for `jamesmacaulay.zelkova.time`.")

     
                                        
      
(defn now [] (.valueOf (js/Date.)))

;;;;;;;;;;;; This file autogenerated from src/cljx/jamesmacaulay/zelkova/impl/time.cljx
